server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/  # Corrected URL for Eureka server
    register-with-eureka: true  # Ensures the client registers with Eureka
    fetch-registry: true  # Fetches registry info from Eureka

spring:
  application:
    name: USER-SERVICE  # The name with which this service will be registered in Eureka

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
